import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from bank_workbook import BankWorkbook

YEARS = ["FY2025", "FY2024", "FY2023", "FY2022", "FY2021"]  # most recent first
YEAR_LABEL = {y: y for y in YEARS}

CH2025_URL = "https://find-and-update.company-information.service.gov.uk/company/06736473/filing-history/MzUyMjY1MjQxM2FkaXF6a2N4/document?format=pdf&download=0"
CH2023_URL = "https://find-and-update.company-information.service.gov.uk/company/06736473/filing-history/MzQyMTM2NzE0MWFkaXF6a2N4/document?format=pdf&download=0"
CH2021_URL = "https://find-and-update.company-information.service.gov.uk/company/06736473/filing-history/MzMzODIzNzc0NWFkaXF6a2N4/document?format=pdf&download=0"

P3_2025_URL = "https://www.bankofceylon.co.uk/downloads/corporate/BOCUK_Pillar%203%20Disclosures%2031%20December%202025.pdf"
P3_2024_URL = "https://www.bankofceylon.co.uk/downloads/corporate/BOCUK_Pillar%203%20Disclosures%2031%20December%202024.pdf"
P3_2021_URL = "https://www.bankofceylon.co.uk/downloads/corporate/BOCUK_Pillar%203%20Disclosures%2031%20December%202021.pdf"

ENTITY_NOTE = (
    "Entity note: Bank of Ceylon (UK) Limited (company 06736473, FRN 514744) is a wholly-owned UK subsidiary of "
    "Bank of Ceylon (Sri Lanka, state-owned). Unlike several other single-country foreign-parented subsidiaries "
    "in this project, it does NOT take the FRS 101/102 cash-flow-statement exemption - a full Statement of Cash "
    "Flows is filed every year, in GBP (no FX conversion needed)."
)

CASH_FLOW_SOURCES = (
    "Sources - all figures are Bank of Ceylon (UK) Limited's own Statement of Cash Flows, £'000, as filed at "
    "Companies House (all 5 filings are fully scanned/image-only - OCR'd with tesseract, cross-verified against "
    "rendered page images at up to 400dpi):\n"
    f"FY2025 & FY2024: Full accounts made up to 31 December 2025, p.27 (Statement of Cash Flows) - {CH2025_URL}\n"
    f"FY2023 & FY2022: Full accounts made up to 31 December 2023, p.42 (Statement of Cashflow) - {CH2023_URL}\n"
    f"FY2021 (& FY2020 comparative, not used): Full accounts made up to 31 December 2021, p.29 (Statement of "
    f"Cashflow) - {CH2021_URL}\n"
    "DATA ERROR NOTE: the FY2021 filing's own printed 'Other assets and derivatives' line for 2021 reads '-761' "
    "(a bare minus sign, inconsistent with every other negative figure in the same column, which uses "
    "parentheses). This does not reconcile with that same document's own printed subtotals ('635' changes-in "
    "subtotal, '927' net operating cash flow) - summing the 7 itemised 'Changes in' lines with -761 gives -887, "
    "not 635. Using +761 instead reconciles exactly to both printed subtotals (635 and 927). +761 is used here; "
    "the original printed '-761' is preserved in this note for reference. The FY2020 comparative column's "
    "equivalent line (-304) is internally consistent as printed and was not changed.\n"
    "PRESENTATION NOTE: both the FY2021 and FY2023 filings mislabel their investing/financing subtotal rows - "
    "the FY2021 filing's 'Net cash flow from financing activities' caption sits directly above the FY2020 "
    "column's investing-activities value (-149, which is actually 'Acquisition of fixed assets'), and the "
    "FY2023 filing's 'Net cash flow from investing activities' caption sits directly above a value that is "
    "actually the operating-activities subtotal (matches 'Cash generated by operations' exactly). Neither year "
    "discloses any financing activity beyond a single investing-classified line ('Acquisition of fixed assets' "
    "FY2021, 'Purchase of operating property, plant and equipment' FY2023/FY2022) or, in FY2022, a genuine "
    "financing line ('Repayment on investments', £747k). This workbook places each line under its correct "
    "economic section (Operating/Investing/Financing) regardless of the source's caption placement; every "
    "section TOTAL and the full opening/closing cash chain reconciles exactly across all 5 years once corrected.\n"
    + ENTITY_NOTE
)


def p3_sources(page_25="3", page_24="4", page_21="12"):
    return (
        "Sources - Bank of Ceylon (UK) Limited Pillar 3 disclosures (own entity-level basis; UK KM1-style Key "
        "Metrics template from FY2022 on, PRA's pre-2022 own-funds/leverage tables for FY2021), £'000 unless "
        "stated:\n"
        f"FY2025 & FY2024 comparative: Pillar 3 Disclosures 31 December 2025, p.{page_25} (1.1 Key Metrics) - {P3_2025_URL}\n"
        f"FY2024 (own year) & FY2023 comparative: Pillar 3 Disclosures 31 December 2024, p.{page_24} (1.1 Key Metrics) - {P3_2024_URL}\n"
        f"FY2021 (own year): Pillar 3 Disclosures as at 31st December 2021, p.{page_21} (4.1 Total Available Capital) - {P3_2021_URL}\n"
        "FY2022: no standalone Pillar 3 document was found on the bank's site (2022 and 2023 editions are both "
        "absent from its published list; FY2023 is covered here only via FY2024's own comparative column) - left "
        "blank rather than guessed.\n"
        "CROSS-VINTAGE NOTE (Leverage Ratio only): the FY2024 Pillar 3 document's own figures for FY2024 (Total "
        "exposure £75,247k, Leverage ratio 18.5%) differ slightly from the FY2025 document's restated FY2024 "
        "comparative (£76,247k, 18.3%). This workbook uses each year's own originally-published figure as the "
        "primary column (FY2024 = 18.5%, from the FY2024 document); the restatement is noted here, not silently "
        "blended. Separately, the FY2025 document's own narrative text states the leverage ratio 'declined from "
        "18.5% to 15.2%' in 2025 - this contradicts both that same document's Key Metrics table and its own "
        "Section 7 reconciliation table, which independently agree at 14.3% (FY2025) / 18.3% (FY2024 restated). "
        "The two internally-consistent tables are used; the narrative sentence appears to be a drafting error.\n"
        + ENTITY_NOTE
    )


bw = BankWorkbook(bank_name="Bank of Ceylon (UK) Limited", years=YEARS, year_label=YEAR_LABEL, header_color="8D6A9F")

# ---------------------------------------------------------------
# Sheet 1: Cash Flow Statement
# ---------------------------------------------------------------
rows = [
    ("SECTION", "Cash flows from operating activities", {}),
    ("DATA", "Profit/(loss) before tax", {"FY2025": 368, "FY2024": 412, "FY2023": 1068, "FY2022": -147, "FY2021": 114}),
    ("DATA", "Depreciation of property, plant and equipment", {"FY2025": 84, "FY2024": 120, "FY2023": 116, "FY2022": 106, "FY2021": 107}),
    ("DATA", "Amortisation of intangible assets", {"FY2025": 14, "FY2024": 10, "FY2023": 9, "FY2022": 11, "FY2021": 12}),
    ("DATA", "Impairment charge/(gain) on loans", {"FY2025": 15, "FY2024": -431, "FY2023": -290, "FY2022": 392, "FY2021": 59}),
    ("DATA", "Loans to customers / Loans and advances to customers", {"FY2025": -19255, "FY2024": -22782, "FY2023": -15946, "FY2022": 1260, "FY2021": 1001}),
    ("DATA", "Financial instruments (assets) / Investments", {"FY2025": 5370, "FY2024": -7861, "FY2023": 6867, "FY2022": 13513, "FY2021": 1760}),
    ("DATA", "Other receivables / other assets and derivatives", {"FY2025": -84, "FY2024": 14, "FY2023": -68, "FY2022": -1112, "FY2021": 761}),
    ("DATA", "Loans and advances to banks", {"FY2021": 92438}),
    ("DATA", "Retail deposits / customer accounts", {"FY2025": 32166, "FY2024": 25309, "FY2023": 7802, "FY2022": 5616, "FY2021": 1079}),
    ("DATA", "Financial instruments (liabilities) / deposits by bank", {"FY2025": -11243, "FY2024": -9670, "FY2023": 30118, "FY2022": 61911, "FY2021": -95893}),
    ("DATA", "Other liabilities and derivatives", {"FY2025": 1013, "FY2024": 635, "FY2023": -617, "FY2022": 1598, "FY2021": -511}),
    ("DATA", "Corporate tax paid", {"FY2025": -87, "FY2024": -179}),
    ("TOTAL", "Net cash flow from operating activities", {"FY2025": 8361, "FY2024": -14423, "FY2023": 29059, "FY2022": 83148, "FY2021": 927}),
    ("SECTION", "Cash flows from investing activities", {}),
    ("DATA", "Purchase of property, plant and equipment / acquisition of fixed assets", {"FY2025": -152, "FY2024": -461, "FY2023": -116, "FY2022": -2, "FY2021": 0}),
    ("TOTAL", "Net cash flow from investing activities", {"FY2025": -152, "FY2024": -461, "FY2023": -116, "FY2022": -2, "FY2021": 0}),
    ("SECTION", "Cash flows from financing activities", {}),
    ("DATA", "Repayment on investments", {"FY2023": 0, "FY2022": 747}),
    ("TOTAL", "Net cash flow from financing activities", {"FY2025": 0, "FY2024": 0, "FY2023": 0, "FY2022": 747, "FY2021": 0}),
    ("TOTAL", "Net increase/(decrease) in cash and cash equivalents", {"FY2025": 8209, "FY2024": -14884, "FY2023": 28943, "FY2022": 83893, "FY2021": 927}),
    ("DATA", "Opening cash and cash equivalents", {"FY2025": 100818, "FY2024": 115702, "FY2023": 86759, "FY2022": 2866, "FY2021": 1939}),
    ("TOTAL", "Closing cash and cash equivalents", {"FY2025": 109027, "FY2024": 100818, "FY2023": 115702, "FY2022": 86759, "FY2021": 2866}),
]

bw.add_cash_flow_sheet(
    title="Bank of Ceylon (UK) Limited — Statement of Cash Flows",
    subtitle="Bank of Ceylon (UK) Limited (own entity basis), £'000 unless stated",
    rows=rows,
    sources_text=CASH_FLOW_SOURCES,
    first_col_width=56,
    source_height=220,
    unit_suffix=" (£'000)",
)

# ---------------------------------------------------------------
# Pillar 3 metric sheets
# ---------------------------------------------------------------
def metric(name, unit, rows_data, note=None):
    bw.add_metric_sheet(name, unit, rows_data, p3_sources(), note=note, first_col_width=46, source_height=200)

metric(
    "CET1 Capital", "£'000",
    [("Common Equity Tier 1 (CET1) capital", {"FY2025": 14217, "FY2024": 13940, "FY2023": 13685, "FY2021": 13424})],
)

metric(
    "CET1 Ratio", "% of RWA",
    [("Common Equity Tier 1 (CET1) ratio", {"FY2025": "20.1%", "FY2024": "22.7%", "FY2023": "42.5%", "FY2021": "54.8%"})],
)

metric(
    "Tier 1 Capital", "£'000",
    [("Tier 1 capital", {"FY2025": 14217, "FY2024": 13940, "FY2023": 13685, "FY2021": 13424})],
    note="BOCUK has no Additional Tier 1 capital in any year - Tier 1 capital equals CET1 capital throughout.",
)

metric(
    "Tier 1 Ratio", "% of RWA",
    [("Tier 1 ratio", {"FY2025": "20.1%", "FY2024": "22.7%", "FY2023": "42.5%", "FY2021": "54.8%"})],
    note="Equal to the CET1 ratio - no Additional Tier 1 capital in any year.",
)

metric(
    "Total Capital", "£'000",
    [("Total capital (own funds)", {"FY2025": 15353, "FY2024": 15076, "FY2023": 14789, "FY2021": 14169})],
)

metric(
    "Total Capital Ratio", "% of RWA",
    [("Total capital ratio", {"FY2025": "21.7%", "FY2024": "24.6%", "FY2023": "45.9%", "FY2021": "57.8%"})],
)

metric(
    "Total RWAs", "£'000",
    [("Total risk-weighted exposure amount", {"FY2025": 70733, "FY2024": 61344, "FY2023": 32187, "FY2021": 24509})],
)

metric(
    "Leverage Ratio", "£'000 / %",
    [
        ("Tier 1 capital available (£'000)", {"FY2025": 14217, "FY2024": 13940, "FY2023": 13685, "FY2021": 13424}),
        ("Total leverage ratio exposure measure (£'000)", {"FY2025": 99213, "FY2024": 75247, "FY2023": 47579, "FY2021": 29072}),
        ("Leverage ratio (%)", {"FY2025": "14.3%", "FY2024": "18.5%", "FY2023": "28.8%", "FY2021": "46.2%"}),
    ],
    note="FY2024 uses the FY2024 Pillar 3 document's own originally-published figures; see the source note above "
         "for the slightly different restated FY2024 comparative (£76,247k / 18.3%) published a year later in "
         "the FY2025 document, and for the FY2025 document's separate self-contradictory narrative text.",
)

metric(
    "LCR", "£'000 / %",
    [
        ("Total high-quality liquid assets (HQLA) (£'000)", {"FY2025": 101212, "FY2024": 99206, "FY2023": 108880}),
        ("Total net cash outflows (£'000)", {"FY2025": 77081, "FY2024": 66349, "FY2023": 86856}),
        ("Liquidity Coverage Ratio (%)", {"FY2025": "131%", "FY2024": "149%", "FY2023": "125%"}),
    ],
    note="Not disclosed for FY2021/FY2022 - the Key Metrics/KM1-style LCR template was not yet used in BOCUK's "
         "FY2021 Pillar 3 disclosure, and no FY2022 document was found (see source note).",
)

metric(
    "NSFR", "£'000 / %",
    [
        ("Total required stable funds (£'000)", {"FY2025": 65823, "FY2024": 64648, "FY2023": 35141}),
        ("Total available stable funds (£'000)", {"FY2025": 121764, "FY2024": 91457, "FY2023": 49594}),
        ("Net Stable Funding Ratio (%)", {"FY2025": "185%", "FY2024": "141%", "FY2023": "141%"})
    ],
    note="FY2023 and FY2024 NSFR ratios are both printed as 141% in the source document despite different "
         "underlying £'000 figures for both years - transcribed as printed, not treated as an error since the "
         "absolute figures genuinely differ. Not disclosed for FY2021/FY2022 (see LCR sheet note; same cause).",
)

bw.add_not_disclosed_metric_sheets(
    ["MREL Ratio"],
    p3_sources(),
    per_note={"MREL Ratio": "Not disclosed in any of the 4 available Pillar 3 editions (FY2021, FY2023 via comparative, FY2024, FY2025), any year - no numeric ratio or explicit exemption statement found."},
)

# ---------------------------------------------------------------
# Overview sheet
# ---------------------------------------------------------------
bw.add_overview_sheet(
    cash_flow_totals=[
        ("Net cash flow from operating activities", {"FY2025": 8361, "FY2024": -14423, "FY2023": 29059, "FY2022": 83148, "FY2021": 927}),
        ("Net cash flow from investing activities", {"FY2025": -152, "FY2024": -461, "FY2023": -116, "FY2022": -2, "FY2021": 0}),
        ("Net cash flow from financing activities", {"FY2025": 0, "FY2024": 0, "FY2023": 0, "FY2022": 747, "FY2021": 0}),
        ("Closing cash and cash equivalents", {"FY2025": 109027, "FY2024": 100818, "FY2023": 115702, "FY2022": 86759, "FY2021": 2866}),
    ],
    cash_flow_unit="£'000",
    ratios=[
        ("CET1 Ratio", {"FY2025": "20.1%", "FY2024": "22.7%", "FY2023": "42.5%", "FY2021": "54.8%"}),
        ("Total Capital Ratio", {"FY2025": "21.7%", "FY2024": "24.6%", "FY2023": "45.9%", "FY2021": "57.8%"}),
        ("Leverage Ratio", {"FY2025": "14.3%", "FY2024": "18.5%", "FY2023": "28.8%", "FY2021": "46.2%"}),
        ("LCR", {"FY2025": "131%", "FY2024": "149%", "FY2023": "125%"}),
        ("NSFR", {"FY2025": "185%", "FY2024": "141%", "FY2023": "141%"}),
    ],
    note="Figures are duplicated from the detail sheets for at-a-glance trend viewing; see each sheet's own "
         "source citation for the underlying document/page. FY2022 Pillar 3 data (all ratios) and FY2021/FY2022 "
         "LCR/NSFR are genuinely absent from the source documents, not omitted in error.",
)

bw.save("/Users/armaan/code/katalysis/banks/BANK OF CEYLON UK FINANCIALS.xlsx")
